# Generated by Django 5.1.1 on 2024-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
